[tool.mypy]
python_version = "3.12"
warn_unused_ignores = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_generics = false
no_implicit_optional = true
pretty = true
# Treat src as import root
mypy_path = "src"

[tool.pytest.ini_options]
testpaths = ["src/ur5_motion/test"]


[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F", "I"]
